// "use client";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuerProvider from "@/Providers/QueryProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang="en">
      <body
        style={{ fontFamily: "Raleway", fontWeight: 600 }}
        className={`${raleway.variable}`}
      >
        <QuerProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
            <Toaster />
          </NextIntlClientProvider>
        </QuerProvider>
      </body>
    </html>
  );
}
